"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const utf8_1 = require("./utf8");
exports.utf8Decode = utf8_1.utf8Decode;
exports.utf8Encode = utf8_1.utf8Encode;
const main_1 = require("./main");
exports.createEncode = main_1.createEncode;
exports.createDecode = main_1.createDecode;
exports.BASE64_TABLE = main_1.BASE64_TABLE;
exports.PAD = main_1.PAD;
const BASE64_URL_TABLE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
exports.BASE64_URL_TABLE = BASE64_URL_TABLE;
const encode = main_1.createEncode(utf8_1.utf8Encode);
exports.encode = encode;
const decode = main_1.createDecode(utf8_1.utf8Decode);
exports.decode = decode;
const encodeURL = main_1.createEncode(BASE64_URL_TABLE, main_1.PAD, utf8_1.utf8Encode);
exports.encodeURL = encodeURL;
const decodeURL = main_1.createDecode(BASE64_URL_TABLE, main_1.PAD, utf8_1.utf8Decode);
exports.decodeURL = decodeURL;
