"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.decodeURL = exports.encodeURL = exports.decode = exports.encode = exports.createDecode = exports.createEncode = exports.utf8Decode = exports.utf8Encode = exports.PAD = exports.BASE64_URL_TABLE = exports.BASE64_TABLE = void 0;
const utf8_1 = require("./utf8");
Object.defineProperty(exports, "utf8Decode", { enumerable: true, get: function () { return utf8_1.utf8Decode; } });
Object.defineProperty(exports, "utf8Encode", { enumerable: true, get: function () { return utf8_1.utf8Encode; } });
const main_1 = require("./main");
Object.defineProperty(exports, "createEncode", { enumerable: true, get: function () { return main_1.createEncode; } });
Object.defineProperty(exports, "createDecode", { enumerable: true, get: function () { return main_1.createDecode; } });
Object.defineProperty(exports, "BASE64_TABLE", { enumerable: true, get: function () { return main_1.BASE64_TABLE; } });
Object.defineProperty(exports, "PAD", { enumerable: true, get: function () { return main_1.PAD; } });
const BASE64_URL_TABLE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
exports.BASE64_URL_TABLE = BASE64_URL_TABLE;
const encode = (0, main_1.createEncode)(utf8_1.utf8Encode);
exports.encode = encode;
const decode = (0, main_1.createDecode)(utf8_1.utf8Decode);
exports.decode = decode;
const encodeURL = (0, main_1.createEncode)(BASE64_URL_TABLE, main_1.PAD, utf8_1.utf8Encode);
exports.encodeURL = encodeURL;
const decodeURL = (0, main_1.createDecode)(BASE64_URL_TABLE, main_1.PAD, utf8_1.utf8Decode);
exports.decodeURL = decodeURL;
